version: "3.4"
services:
  web:
    image: webcore:3
    ports:
      - 8000:80
    depends_on:
      - db
      - redis
  
  db:
    image: db:5

  redis:
    image: redis:alpine

networks:
  default:
    external:
      name: nat