FROM microsoft/aspnetcore-build:2.0 AS build-env

WORKDIR /app
COPY . ./

WORKDIR /app/Web
RUN pwd

RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=build-env /app/Web/out .
ENTRYPOINT ["dotnet", "Web.dll"]

ENV REDIS_CONNECTIONSTRING localhost:6379